### ISSUE TITLE
Cookie retrieved but it cannot be console logged

### ISSUE THREAD

**Issue by trancephorm** [WhereCanI/svelte-cookie#1]
It's dead simple, but it just doesn't work here, and I'm absolutely sure cookie is sent with request because I checked headers in Inspector console. The only difference is that cookie is from localhost:4567, and I have Svelte app on localhost:8080.
```
	import { getCookie } from 'svelte-cookie';
	let cookie = getCookie("express.sid");
	console.log(typeof(cookie));  // outputs string (so it does exist and it is defined)
	console.log(cookie);  // outputs empty row in console!?
```
Can someone please enlighten me?

**Comment by WhereCanI** [comment]
Hmm, I have run into this sometimes when retrieving cookies from the browser. Does this also happen if you use await or a promise when you save the value to a variable? 

Like this:
`let cookie = await getCookie("express.sid");`

Or:
`getCookie("express.sid").then(val => console.log(val));`

I am suspecting that the reason it comes out empty is that the cookie is sent to the console before it receives the value. It is a function that retrieves the cookie value and if the value is not set before it is written in the console, then it might be empty. The same thing can happen when doing fetch functions getting data from an API.

Please let me know if it helped using either await or a promise.

**Comment by trancephorm** [comment]
I get getCookie(...).then is not a function

I doubt it will work with await if doesn't work like this?

**Comment by trancephorm** [comment]
...and if typeof is string, that means it's defined aleady. So weird.

**Comment by WhereCanI** [comment]
Does the cookie have a value if you check in the inspector in your browser?

Also, can I get you to try the async await to see if you get the value then?

**Comment by trancephorm** [comment]
Yes, in cookies section it's displayed:
![image](https://user-images.githubusercontent.com/5833909/152773456-0270b460-9338-42fc-be0f-1e1178993096.png)

When I try to execute it with await like this, that whole block is not executed, I don't have slightest idea why:
`(async () => {
  let cookie = await getCookie("express.sid");
  console.log("App.svelte, cookie:");
  console.log(cookie);
});`

**Comment by WhereCanI** [comment]
What about if you use the onMount function from Svelte like this? When I do it this way the function is running and I get the value.

```
import {onMount} from 'svelte';

onMount(() => {
		getCookieVal();
});

async function getCookieVal() {
   let cookie = await getCookie("express.sid");
   console.log(cookie);
}

```

**Comment by trancephorm** [comment]
Already tried that both with onMount and afterUpdate ... it's just not outputting anything.

**Comment by WhereCanI** [comment]
Hmm that seems odd. Can you please make a codepen or something similar where the problem is recreated and post it here, then I can see if something should be wrong. I tried recreating locally but for me it is working.

**Comment by trancephorm** [comment]
I doubt codepen or anything else can run Svelte application, but what I did is I just inserted those few lines of code in Svelte Hello World app, even making it run on the same port as the site that emmited cookie was running (NodeBB forum, it's expressjs session cookie as far as I understand), it's still the same: typeof(cookie) gives string, but nothing is when you just try to console log it. Cookie is there listed, I'm absolutely mazed and I think I'm giving up reading that cookie - will just make login and that's it. God knows how many problems would be if cookie is to be read from another subdomain... :) I think finally this has something to do with security in browsers.

I just tried it in Firefox, and instead of empty line in console it gives "empty string"

**Comment by WhereCanI** [comment]
Yes it probably could be something with security in the browser or maybe that it's an express session cookie. 

Does it also happen if you create a cookie with for example a string saying "Hello” and try to write that to the console? If it is working with other types of cookies then it's most likely the session cookie that requires something special.

**Comment by trancephorm** [comment]
Yes, it is express session cookie. Working around this problem for now, but it's possible I will be back to it in future. If you conclude something, please tell here.

**Comment by trancephorm** [comment]
Tried with a normal cookie I made and it works. Concluded express.sid cookie from NodeBB can't be seen because it has some security enabled, I think SameSite property is the culprit. BTW, that property of session cookie cannot be regularily changed in NodeBB as far as I can see.
